# Generated by Django 3.2.8 on 2022-04-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.CharField(max_length=14)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=14, unique=True)),
                ('weight', models.CharField(max_length=4)),
                ('height', models.CharField(max_length=4)),
                ('allergies', models.BooleanField()),
                ('Age', models.IntegerField()),
                ('Med1', models.CharField(default='Medician 1', max_length=24)),
                ('Med2', models.CharField(default='Medician 2', max_length=24)),
                ('Med3', models.CharField(default='Medician 3', max_length=24)),
                ('Med4', models.CharField(default='Medician 4', max_length=24)),
                ('Med5', models.CharField(default='Medician 5', max_length=24)),
                ('Med6', models.CharField(default='Medician 6', max_length=24)),
                ('Med7', models.CharField(default='Medician 7', max_length=24)),
                ('Med8', models.CharField(default='Medician 8', max_length=24)),
                ('time_1', models.TimeField(blank=True, null=True)),
                ('time_2', models.TimeField(blank=True, null=True)),
                ('time_3', models.TimeField(blank=True, null=True)),
                ('time_4', models.TimeField(blank=True, null=True)),
                ('time_5', models.TimeField(blank=True, null=True)),
                ('time_6', models.TimeField(blank=True, null=True)),
                ('time_7', models.TimeField(blank=True, null=True)),
                ('time_8', models.TimeField(blank=True, null=True)),
                ('pills_1', models.IntegerField(blank=True, null=True)),
                ('pills_2', models.IntegerField(blank=True, null=True)),
                ('pills_3', models.IntegerField(blank=True, null=True)),
                ('pills_4', models.IntegerField(blank=True, null=True)),
                ('pills_5', models.IntegerField(blank=True, null=True)),
                ('pills_6', models.IntegerField(blank=True, null=True)),
                ('pills_7', models.IntegerField(blank=True, null=True)),
                ('pills_8', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
